import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import './globals.css';
import Nav from '@/components/Nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto_mono = Roboto_Mono({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto_mono.variable} antialiased`}>
        <div className="min-h-screen w-full bg-background flex flex-col">
          <Nav />
          <main className="">{children}</main>
          <footer className=""></footer>
        </div>
      </body>
    </html>
  );
}
